import { useState, useRef, useEffect } from 'react';
import {
  View, Text, StyleSheet, Pressable, Alert,
  Animated, ActivityIndicator,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { CameraView, useCameraPermissions } from 'expo-camera';
import * as ImagePicker from 'expo-image-picker';
import * as FileSystem from 'expo-file-system';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { useThemeContext } from '@/theme/ThemeContext';
import { validateProtectedText } from '@/crypto/validation';
import { haptics } from '@/services/hapticService';
import { FONTS, FONT_SIZE } from '@/constants/typography';
import { RADIUS, SPACING } from '@/constants/spacing';

// Pure-JS QR decoder — reads the canvas pixel data from an image URI
async function decodeQRFromUri(uri: string): Promise<string | null> {
  try {
    // Use expo-camera's built-in ability to scan a static image isn't available,
    // so we use a manual approach: read as base64 and pass to a JS QR library.
    // We use the jsQR approach via a simple fetch/canvas mock in Hermes.
    // Instead, we use a more reliable approach: import the image and decode it
    // via the expo-camera scanFromURLAsync if available, otherwise fall back.
    const { scanFromURLAsync } = await import('expo-camera');
    if (typeof scanFromURLAsync === 'function') {
      const results = await scanFromURLAsync(uri, ['qr']);
      if (results && results.length > 0) {
        return results[0].data;
      }
    }
    return null;
  } catch {
    return null;
  }
}

export default function QRScanScreen() {
  const router = useRouter();
  const { colors } = useThemeContext();
  const [permission, requestPermission] = useCameraPermissions();
  const [scanned, setScanned] = useState(false);
  const [mode, setMode] = useState<'camera' | 'gallery'>('camera');
  const [processing, setProcessing] = useState(false);
  const [torch, setTorch] = useState(false);
  const scanLineAnim = useRef(new Animated.Value(0)).current;

  // Animate scan line
  useEffect(() => {
    Animated.loop(
      Animated.sequence([
        Animated.timing(scanLineAnim, { toValue: 1, duration: 2000, useNativeDriver: true }),
        Animated.timing(scanLineAnim, { toValue: 0, duration: 2000, useNativeDriver: true }),
      ])
    ).start();
  }, []);

  const handleResult = (data: string) => {
    haptics.success();
    if (validateProtectedText(data)) {
      router.replace({ pathname: '/open', params: { prefill: data } });
    } else {
      Alert.alert(
        'Not a Protected Message',
        'This QR code does not contain an ADEVeil protected message. Make sure the QR was generated by ADEVeil.',
        [
          { text: 'Try Again', onPress: () => setScanned(false) },
          { text: 'Cancel', style: 'cancel', onPress: () => router.back() },
        ]
      );
    }
  };

  const handleBarCodeScanned = ({ data }: { data: string }) => {
    if (scanned || processing) return;
    setScanned(true);
    handleResult(data);
  };

  const handlePickFromGallery = async () => {
    haptics.light();
    setProcessing(true);
    try {
      const result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        quality: 1,
        allowsEditing: false,
      });

      if (result.canceled || !result.assets?.[0]) {
        setProcessing(false);
        return;
      }

      const uri = result.assets[0].uri;
      const decoded = await decodeQRFromUri(uri);

      if (decoded) {
        handleResult(decoded);
      } else {
        haptics.error();
        Alert.alert(
          'No QR Code Found',
          'Could not detect an ADEVeil QR code in this image. Try a clearer photo with the QR code fully visible.',
          [{ text: 'Try Another Image', onPress: () => setProcessing(false) }]
        );
      }
    } catch {
      haptics.error();
      Alert.alert('Error', 'Could not read the image. Please try again.');
      setProcessing(false);
    }
  };

  // ─── Permission screen ─────────────────────────────────────────────────────
  if (!permission) return <View style={styles.container} />;

  if (!permission.granted) {
    return (
      <View style={[styles.container, { backgroundColor: colors.bg }]}>
        <SafeAreaView style={styles.centered}>
          <LinearGradient
            colors={colors.gradientPurple}
            style={styles.permIcon}
            start={{ x: 0, y: 0 }}
            end={{ x: 1, y: 1 }}
          >
            <Ionicons name="camera-outline" size={36} color="#fff" />
          </LinearGradient>
          <Text style={[styles.permTitle, { color: colors.text }]}>Camera Access Needed</Text>
          <Text style={[styles.permDesc, { color: colors.textMuted }]}>
            ADEVeil needs camera access to scan QR codes. No images are stored or shared.
          </Text>
          <Pressable onPress={requestPermission} style={[styles.permBtn, { backgroundColor: colors.accent }]}>
            <Text style={styles.permBtnText}>Allow Camera</Text>
          </Pressable>
          <Text style={[styles.orText, { color: colors.textMuted }]}>— or —</Text>
          <Pressable
            onPress={handlePickFromGallery}
            style={[styles.galleryBtn, { borderColor: colors.border, backgroundColor: colors.surface }]}
          >
            <Ionicons name="images-outline" size={20} color={colors.accent} />
            <Text style={[styles.galleryBtnText, { color: colors.text }]}>Pick from Gallery</Text>
          </Pressable>
          <Pressable onPress={() => router.back()} hitSlop={12}>
            <Text style={[styles.cancelText, { color: colors.textDim }]}>Cancel</Text>
          </Pressable>
        </SafeAreaView>
      </View>
    );
  }

  // ─── Camera scan screen ────────────────────────────────────────────────────
  const scanLineY = scanLineAnim.interpolate({ inputRange: [0, 1], outputRange: [0, FRAME - 4] });

  return (
    <View style={styles.container}>
      <CameraView
        style={StyleSheet.absoluteFill}
        facing="back"
        enableTorch={torch}
        onBarcodeScanned={scanned || processing ? undefined : handleBarCodeScanned}
        barcodeScannerSettings={{ barcodeTypes: ['qr'] }}
      />

      {/* Dark overlay corners */}
      <View style={styles.overlayTop} />
      <View style={styles.overlayMiddle}>
        <View style={styles.overlaySide} />
        <View style={styles.scanFrame}>
          {/* Animated scan line */}
          <Animated.View style={[styles.scanLine, { transform: [{ translateY: scanLineY }] }]} />
          {/* Corner marks */}
          <View style={[styles.corner, styles.tl]} />
          <View style={[styles.corner, styles.tr]} />
          <View style={[styles.corner, styles.bl]} />
          <View style={[styles.corner, styles.br]} />
        </View>
        <View style={styles.overlaySide} />
      </View>
      <View style={styles.overlayBottom} />

      {/* Top bar */}
      <SafeAreaView style={StyleSheet.absoluteFill} pointerEvents="box-none">
        <View style={styles.topBar}>
          <Pressable onPress={() => router.back()} style={styles.topBtn}>
            <Ionicons name="close" size={22} color="#fff" />
          </Pressable>
          <Text style={styles.topTitle}>Scan QR Code</Text>
          <Pressable onPress={() => { haptics.light(); setTorch(t => !t); }} style={styles.topBtn}>
            <Ionicons name={torch ? 'flash' : 'flash-outline'} size={22} color={torch ? '#FBBF24' : '#fff'} />
          </Pressable>
        </View>

        {/* Hint */}
        <View style={styles.hintRow}>
          <Text style={styles.hintText}>Point the camera at an ADEVeil QR code</Text>
        </View>

        {/* Bottom actions */}
        <View style={styles.bottomBar}>
          {processing ? (
            <View style={styles.processingRow}>
              <ActivityIndicator color="#fff" />
              <Text style={styles.processingText}>Reading QR code…</Text>
            </View>
          ) : (
            <Pressable onPress={handlePickFromGallery} style={styles.galleryFloatBtn}>
              <Ionicons name="images-outline" size={22} color="#fff" />
              <Text style={styles.galleryFloatText}>Choose from Gallery</Text>
            </Pressable>
          )}

          {scanned && !processing && (
            <Pressable onPress={() => setScanned(false)} style={styles.rescanBtn}>
              <Text style={styles.rescanText}>Scan Again</Text>
            </Pressable>
          )}
        </View>
      </SafeAreaView>
    </View>
  );
}

const FRAME = 260;
const CORNER_SIZE = 28;
const BORDER_W = 3;
const OVERLAY_COLOR = 'rgba(0,0,0,0.62)';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },

  // Permission screen
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: SPACING.xl, gap: SPACING.lg },
  permIcon: { width: 80, height: 80, borderRadius: 24, alignItems: 'center', justifyContent: 'center', marginBottom: SPACING.sm },
  permTitle: { fontFamily: FONTS.bold, fontSize: FONT_SIZE.xl, textAlign: 'center' },
  permDesc: { fontFamily: FONTS.regular, fontSize: FONT_SIZE.md, textAlign: 'center', lineHeight: 22 },
  permBtn: { paddingVertical: 14, paddingHorizontal: 40, borderRadius: RADIUS.full },
  permBtnText: { fontFamily: FONTS.semiBold, fontSize: FONT_SIZE.md, color: '#fff' },
  orText: { fontFamily: FONTS.regular, fontSize: FONT_SIZE.sm },
  galleryBtn: {
    flexDirection: 'row', alignItems: 'center', gap: SPACING.sm,
    paddingVertical: 12, paddingHorizontal: 28,
    borderRadius: RADIUS.full, borderWidth: 1,
  },
  galleryBtnText: { fontFamily: FONTS.medium, fontSize: FONT_SIZE.md },
  cancelText: { fontFamily: FONTS.regular, fontSize: FONT_SIZE.sm, marginTop: SPACING.xs },

  // Overlay darkening
  overlayTop: { height: '20%', backgroundColor: OVERLAY_COLOR },
  overlayMiddle: { flexDirection: 'row', height: FRAME },
  overlaySide: { flex: 1, backgroundColor: OVERLAY_COLOR },
  overlayBottom: { flex: 1, backgroundColor: OVERLAY_COLOR },

  // Scan frame
  scanFrame: {
    width: FRAME, height: FRAME, position: 'relative', overflow: 'hidden',
  },
  scanLine: {
    position: 'absolute', left: 0, right: 0, height: 2,
    backgroundColor: '#6B5CE7', opacity: 0.85,
    shadowColor: '#6B5CE7', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 1, shadowRadius: 6,
  },
  corner: {
    position: 'absolute', width: CORNER_SIZE, height: CORNER_SIZE,
    borderColor: '#fff', borderWidth: BORDER_W,
  },
  tl: { top: 0, left: 0, borderBottomWidth: 0, borderRightWidth: 0, borderTopLeftRadius: 4 },
  tr: { top: 0, right: 0, borderBottomWidth: 0, borderLeftWidth: 0, borderTopRightRadius: 4 },
  bl: { bottom: 0, left: 0, borderTopWidth: 0, borderRightWidth: 0, borderBottomLeftRadius: 4 },
  br: { bottom: 0, right: 0, borderTopWidth: 0, borderLeftWidth: 0, borderBottomRightRadius: 4 },

  // Top bar
  topBar: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: SPACING.lg, paddingVertical: SPACING.md,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  topBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  topTitle: { fontFamily: FONTS.semiBold, fontSize: FONT_SIZE.lg, color: '#fff' },

  // Hint
  hintRow: { alignItems: 'center', marginTop: SPACING.sm },
  hintText: {
    fontFamily: FONTS.regular, fontSize: FONT_SIZE.sm,
    color: 'rgba(255,255,255,0.75)',
    backgroundColor: 'rgba(0,0,0,0.4)',
    paddingHorizontal: 16, paddingVertical: 6, borderRadius: RADIUS.full,
  },

  // Bottom
  bottomBar: {
    position: 'absolute', bottom: 0, left: 0, right: 0,
    paddingBottom: 40, paddingHorizontal: SPACING.xl, gap: SPACING.md,
    alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.55)',
    paddingTop: SPACING.xl,
  },
  galleryFloatBtn: {
    flexDirection: 'row', alignItems: 'center', gap: SPACING.sm,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderWidth: 1, borderColor: 'rgba(255,255,255,0.3)',
    paddingVertical: 12, paddingHorizontal: 28, borderRadius: RADIUS.full,
  },
  galleryFloatText: { fontFamily: FONTS.medium, fontSize: FONT_SIZE.md, color: '#fff' },
  processingRow: { flexDirection: 'row', alignItems: 'center', gap: SPACING.md },
  processingText: { fontFamily: FONTS.regular, fontSize: FONT_SIZE.md, color: '#fff' },
  rescanBtn: {
    backgroundColor: 'rgba(107,92,231,0.8)',
    paddingVertical: 10, paddingHorizontal: 28, borderRadius: RADIUS.full,
  },
  rescanText: { fontFamily: FONTS.semiBold, fontSize: FONT_SIZE.md, color: '#fff' },
});
